# Generated by Django 4.0.4 on 2022-05-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_calibre', models.CharField(max_length=45, unique=True, verbose_name='Descrição do calibre')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoTipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_objeto', models.CharField(max_length=64, unique=True, verbose_name='Tipo de objeto')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetotipomodel', verbose_name='Objeto tipo')),
            ],
        ),
        migrations.CreateModel(
            name='MunicaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('valor_estimado', models.FloatField(verbose_name='Valor estimado')),
                ('calibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calibremodel', verbose_name='Calibre')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetomodel', verbose_name='Objeto')),
            ],
        ),
        migrations.CreateModel(
            name='ArmaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('quantidade_de_tiros', models.IntegerField(verbose_name='Quantidade de tiros')),
                ('valor_estimado', models.FloatField(verbose_name='Valor estimado')),
                ('imagem', models.ImageField(upload_to='')),
                ('calibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calibremodel', verbose_name='Calibre')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objetomodel', verbose_name='Objeto')),
            ],
        ),
    ]
