# Generated by Django 4.0.4 on 2022-05-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibremodel',
            name='desc_calibre',
            field=models.CharField(max_length=45, unique=True, verbose_name='Descrição do calibre'),
        ),
        migrations.AlterField(
            model_name='objeto_tipomodel',
            name='tipo_de_objeto',
            field=models.CharField(max_length=64, unique=True, verbose_name='Tipo de objeto'),
        ),
    ]
