# Generated by Django 4.0.4 on 2022-05-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_calibremodel_desc_calibre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objeto_tipoModel',
            new_name='ObjetoTipoModel',
        ),
    ]
